/**
 * 消息模板常量
 *
 * 统一管理整个框架中的消息模板
 *
 * 使用方式：
 * ```typescript
 * import { MESSAGES } from '../macro/Message';
 *
 * // 在 GUI 服务中使用
 * export class Gui {
 *   private _logView(message: string, ...args: any[]) {
 *     console.log(MESSAGES.GUI.CATEGORY + message, ...args);
 *   }
 * }
 * ```
 */
export const MESSAGES = {
  SERVICE: {
    CATEGORY: '🛎️ 服务容器:',
    FACTORY_EXISTED: '工厂方法 {0} 已存在，将被覆盖',
    FACTORY_REGISTERED: '注册工厂方法 {0}',
    INSTANCE_EXISTED: '实例对象 {0} 已存在，将被覆盖',
    INSTANCE_REGISTERED: '注册实例对象 {0}',
    NOT_REGISTERED: '该工厂方法或实例对象未注册 {0}',
    CREATE_INSTANCE: '创建实例对象 {0}',
  },
  APP_LAUNCHER: {
    CATEGORY: '🚀 启动器:',
    INVALID_ROOT: '根节点未正确配置',
    INVALID_2D_CAMERA: '2D相机节点未正确配置',
    CAMERA_NEEDED: '2D相机节点下必须挂载 Camera',
    CANVAS_NEEDED: '根节点下必须挂载 Canvas',
    ENTER_FOREGROUND: '回到前台，耗时: {0} 秒',
    ENTER_BACKGROUND: '进入后台',
    SCREEN_SIZE_CHANGED: '屏幕尺寸改变',
    SCREEN_ORIENTATION_CHANGED: '屏幕方向改变',
    SCREEN_TAPPED: '点击屏幕 {0},{1}',
    OUT_OF_MEMORY: '内存不足',
  },
  ARG_PARSER: {
    CATEGORY: '🔓 参数解析器:',
    APP_ARGS: '应用参数',
  },
  ASCENDING_ID: {
    CATEGORY: '🆔 编号:',
    CREATED: '第一次创建 {0} -> {1}',
  },
  ASTC: {
    CATEGORY: '🧩 ASTC:',
    DOWNLOAD_OK: '下载成功',
    DOWNLOAD_BAD: '下载失败',
    PARSE_OK: '解析成功',
    PARSE_BAD: '解析失败',
    CREATE_OK: '创建成功',
    CREATE_BAD: '创建失败',
  },
  AUDIO_PLAYER: {
    CATEGORY: '🔊 音频:',
    MUSIC_PLAYING: '🎵 音乐正在播放中 {0}',
  },
  CATCHER: {
    CATEGORY: '🪰 异常捕获:',
    ASYNC_ERROR: '异步错误',
    SYNC_ERROR: '同步错误',
  },
  EVENT_BUS: {
    CATEGORY: '🚌 事件总线:',
  },
  GLOBAL_ADAPTER: {
    CATEGORY: '⚽ 全局对象:',
    REPLACE: '替换属性 {0}，请注意影响范围',
    ADD: '添加属性 {0}',
    DELETE: '删除属性 {0}',
  },
  GUI: {
    CATEGORY: '📷 视图:',
    REGISTERED: '{0} 已经注册',
    REGISTER_DUPLICATE: '{0} 重复注册, 已跳过',
    REGISTER_REPLACED: '{0} 已经注册, 已替换',
    UNREGISTERED: '{0} 未注册',
    CREATE_PARENT_INVALID: '{0} 创建实例失败，父节点无效',
    CREATE_CONFIG_INVALID: '{0} 创建实例失败，配置无效',
    CREATE_PREFAB_INVALID: '{0} <{1}> 创建实例失败，未能正确识别预制体',
    INSTANCE_FROM_CACHE: '{0} 从缓存创建',
    INSTANCE_FROM_PREFAB: '{0} 从实例创建',
    INSTANCE_CLOSED: '{0} 关闭',
    ANIMATION_ENTER: '{0} 播放进入动画 {1}',
    ANIMATION_EXIT: '{0} 播放退出动画 {1}',
    FETCH_CONFIG_INVALID: '参数无效',
    FETCH_CONFIG_TYPE_UNSUPPORTED: '不支持的参数类型: {0}',
    CLICK_AT_MASK: '点击到 {0} 遮罩',
    CHECK_OWN_LAYER: '{0} 层级不符 {1} != {2}，请检查',
    OPEN_YET: '已经打开,请勿重复操作 {0}',
    CLOSE_BAD_NOT_FOUND: '关闭无效,未找到指定视图 {0}',
    CLOSE_BAD_INVALID_CONFIG: '关闭无效,请检查参数',
    CLOSE_BAD_UNDER_DEPTH: '关闭无效，深度小于 0',
    CLOSE_BAD_OVER_DEPTH: '关闭无效，深度大于栈内深度',
    CLOSE_BAD_EMPTY_STACK: '关闭无效，栈内已无视图',
    CLOSE_BAD_NOT_EXISTED: '关闭无效，视图不存在，深度 {0}',
    FORCE_CLOSE_SCREEN_TIP: 'Screen 栈内仅剩最后一个实例，如果坚持关闭，请使用 close(true)',
    PARSE_BIND_1: '解析绑定配置，索引节点未找到， key={0}, path={1}',
    PARSE_BIND_2: '解析绑定配置，索引组件未找到， key={0}, path={1}',
  },
  HTTP: {
    CATEGORY: '🏄 Http:',
    QUEUED: '请求进入队列: {0}',
    RETRYING: '请求重试 ({0}/{1}): {2}',
    NETWORK_ERROR: '网络错误',
    TIMEOUT: '请求超时',
    CANCELLED: '请求已取消',
    PARSE_ERROR: '响应解析错误',
    SEND_ERROR: '请求发送失败',
    CONCURRENCY_LIMIT_EXCEEDED: '请求队列已满',
  },
  LOCALIZATION: {
    CATEGORY: '🌏 国际化:',
    ID_NOT_FOUND: '未找到文本编号 {0}',
    ID_NOT_FOUND_IN_DICT: '在字典 {0} 中未找到文本编号 {1}',
    USE_CACHE: '使用本地缓存的语言 {0}',
    USE_SYSTEM: '使用系统默认的语言 {0}',
    USE_PASS_IN: '使用用户传入的语言 {0}',
    ADD_DICT: '添加语言包 {0}',
    UPDATE_DICT: '更新语言包 {0}',
    DEL_DICT: '删除语言包 {1}',
  },
  NODE_POOL: {
    CATEGORY: '🫙 节点池：',
    REGISTER_BAD_EXISTED: '注册失败，目标已存在 {0}',
    REGISTER_BAD_DISMATCHED: '注册失败，目标实例不符合条件 {0}',
    QUERY_BAD_NOT_FOUND: '查询失败，目标不存在 {0}',
    RECYCLE_BAD_NOT_FOUND: '回收失败，目标不存在 {0}',
    RECYCLE_OK: '回收节点到池子 {0}',
  },
  OBJECT_POOL: {
    CATEGORY: '🍺 对象池:',
    REGISTER_BAD_EXISTED: '注册失败，目标已存在 {0}',
    UN_REGISTER_OK: '注销成功 {0}',
    NOT_REGISTERED: '目标未注册 {0}',
    RECYCLE_OK: '回收对象到池子 {0}',
  },
  PLATFORM: {
    CATEGORY: '💻 平台:',
  },
  PROFILER: {
    CATEGORY: '📊 性能分析器:',
    TEXTURE_DETAILS: '纹理日志',
    MEMORY_OCCUPY: '占用内存 {0}M',
  },
  RED_DOT: {
    CATEGORY: '🔴 红点:',
    REGISTER_BAD_EXISTED: '注册失败，目标已存在 {0}',
    REGISTER_OK: '注册成功 {0}',
    UPDATE_BAD_NOT_REGISTERED: '更新失败，目标未注册 {0}',
    UPDATE_BAD_EMPTY_DATA: '更新失败，数据不存在 {0}',
    TRIGGER_BAD_NOT_REGISTERED: '触发失败，目标未注册 {0}',
    UN_REGISTER_OK: '目标注销成功 {0}',
    EXECUTE_BAD_IN_STATE_CHANGED: '目标状态变化回调执行失败',
    RESTORE_OK: '目标持久化恢复成功 {0}',
    RESTORE_BAD: '目标持久化恢复失败 {0}:{1}',
    PERSIST_OK: '目标持久化失败 {0}',
    PERSIST_BAD: '目标持久化失败 {0}:{1}',
  },
  RES_CACHE: {
    CATEGORY: '🗄️资源缓存:',
    CACHE_BAD: '资源无效，无法缓存 {0}',
    CACHE_OK: '资源 {0}，预设 {1}s 后过期',
    ACQUIRE_BAD_NOT_CACHED: '资源未缓存 {0}',
    ACQUIRE_BAD_INVALID: '资源已失效 {0}',
    ACQUIRE_BAD_HAS_EXPIRED: '资源已过期 {0}',
    RELEASE: '释放资源 {0}',
    DELETE: '删除资源 {0}',
    ADD_REF: '增持 {0} 计数:{1}',
    DEC_REF: '减持 {0} 计数:{1}',
    CLEAN_UNUSED: '清理过期资源 {0} 个 => {1}',
    CLEAN_CACHE: '清理缓存资源 {0} 个',
    CLEAN_SOURCE: '清理来自 {0} 的资源 {1} 个',
  },
  RES_LOADER: {
    CATEGORY: '🏃‍♂️‍➡️ 资源加载:',
    UNLOAD: '卸载资源包 {0}',
    PRELOAD_BAD: '预加载失败 {0}',
    PRELOAD_DONE: '预加载完成 {0}/{1}',
    SKIP_INVALID_PATH: '跳过无效路径 {0}',
    TARGETED: '命中缓存 {0}',
    LOAD_AND_CACHE: '加载并缓存 {0}',
    LOAD_BAD: '加载失败 {0}',
    LOAD_DONE: '加载完成 {0}/{1} 资源列表:\n {2}',
    LOAD_BAD_2: '资源包不存在 {0}',
    LOAD_BAD_3: '资源包加载失败 => {0}',
    LOAD_BAD_4: '加载失败 {0}@{1}',
    LOAD_BAD_5: '不支持的远程资源类型 {0}',
  },
  RICH_TEXT_ATLAS: {
    CATEGORY: '📔 富文本图集:',
    EXISTED: '{0} 已配置为 {1}，请注意合理分配图集标识和等级',
    ADD: '添加 {0} => {1}',
    CLICK_LINK: '点击到链接: {0}',
  },
  SENSITIVES: {
    CATEGORY: '🔞 敏感词:',
  },
  STORE: {
    CATEGORY: '💾 持久化:',
  },
  TABLE_QUERY: {
    CATEGORY: '📰 表格:',
    PARSE_BAD: '解析失败，目标未注册 {0}',
    PARSE_OK: '解析成功 {0}',
    QUERY_BAD_NOT_REGISTERED: '查询失败，目标未注册 {0}',
    QUERY_BAD_NO_DATA: '查询失败，目标无数据 {0}',
  },
  TIMER: {
    CATEGORY: '🕰️ 计时器:',
  },
  TWEENER: {
    CATEGORY: '🖼️ 缓动:',
    REGISTER_REPLACE: '注册成功，使用最新版本 {0}',
    REGISTER_NEW: '注册成功 {0}',
    NOT_REGISTERED: '目标未注册 {0}',
    EXECUTE_BAD: '执行异常 {0} => {1}',
    ON_START_BAD: 'onStart 回调异常 {0} => {1}',
    ON_PAUSE_BAD: 'onPause 回调异常 {0} => {1}',
    ON_RESUME_BAD: 'onResume 回调异常 {0} => {1}',
    ON_STOP_BAD: 'onStop 回调异常 {0} => {1}',
    ON_END_BAD: 'onEnd 回调异常 {0} => {1}',
    BUILD_BAD: '构建失败 {0} => {1}',
    IS_PLAYING_SKIP: '正在播放中，应用跳过策略 {0}',
    IS_PLAYING_REPLACE: '正在播放中，应用替换策略 {0}',
  },
  TRIGGER: {
    RUNTIME_ERROR: '❌ 触发器: 运行时错误 => {0}',
  },
  WEBSOCKET: {
    CATEGORY: '🛜 Websocket:',
    CONNECTING: '正在连接 {0}',
    CONNECTED: '连接成功 {0}',
    DISCONNECTED: '连接已断开',
    CONNECTION_FAILED: '连接失败 {0}',
    RECONNECTING: '重连中 ({0}/{1}): {2}',
    RECONNECTED: '重连成功 (第{0}次尝试)',
    RECONNECT_FAILED: '重连失败，已达到最大尝试次数 {0}',
    SEND_MESSAGE: '发送消息 {0}',
    SEND_ONE_WAY: '发送单向消息 {0}',
    SEND_BATCH: '批量发送 {0} 条消息',
    RECEIVE_MESSAGE: '收到消息 {0}',
    REQUEST_TIMEOUT: '请求超时 {0}',
    REQUEST_CANCELLED: '请求已取消 {0}',
    REQUEST_FAILED: '请求失败 {0}',
    HEARTBEAT_SENT: '发送心跳包',
    HEARTBEAT_RECEIVED: '收到心跳响应，延迟 {0}ms',
    HEARTBEAT_TIMEOUT: '心跳超时',
    PARSING_MESSAGE: '解析消息 {0}',
    PARSE_ERROR: '消息解析失败 {0}',
    QUEUE_REQUEST: '请求进入队列: {0}',
    CONCURRENCY_LIMIT: '并发请求数已达上限: {0}/{1}',
    CLEAR_REQUESTS: '清理 {0} 个待处理请求',
    INTERCEPTOR_ERROR: '拦截器执行失败 {0}',
    ERROR_CODE_1: '连接正在进行中',
    ERROR_CODE_2: '请求拦截器执行失败',
    ERROR_CODE_3: '请求已取消',
    ERROR_CODE_4: '请求已关闭',
    ERROR_CODE_5: '发送消息失败',
    ERROR_CODE_6: '连接已关闭',
    ERROR_CODE_7: '请求超时',
    ERROR_CODE_8: '连接超时',
    ERROR_CODE_9: '连接错误',
    ERROR_CODE_10: '心跳超时',
    ERROR_CODE_11: '发送心跳失败',
    ERROR_CODE_12: '事件 "{0}" 监听器执行失败',
    PROTOCOL_NOT_FOUND: '协议未注册 {0}',
    PROTOCOL_RESP_UNEXPECTED: '协议解码器未注册或该请求不需要响应但被意外响应了 {0}',
  },
} as const;
