// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.31.0
// source: proto/game.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "proto.game";

/** 消息号 */
export enum MsgId {
  /** HeartBeat - 心跳 */
  HeartBeat = 0,
  Ping = 1,
  Pong = 2,
  UNRECOGNIZED = -1,
}

export function msgIdFromJSON(object: any): MsgId {
  switch (object) {
    case 0:
    case "HeartBeat":
      return MsgId.HeartBeat;
    case 1:
    case "Ping":
      return MsgId.Ping;
    case 2:
    case "Pong":
      return MsgId.Pong;
    case -1:
    case "UNRECOGNIZED":
    default:
      return MsgId.UNRECOGNIZED;
  }
}

export function msgIdToJSON(object: MsgId): string {
  switch (object) {
    case MsgId.HeartBeat:
      return "HeartBeat";
    case MsgId.Ping:
      return "Ping";
    case MsgId.Pong:
      return "Pong";
    case MsgId.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 错误码 */
export enum ErrCode {
  SUCCESS = 0,
  FAIL = 1,
  UNRECOGNIZED = -1,
}

export function errCodeFromJSON(object: any): ErrCode {
  switch (object) {
    case 0:
    case "SUCCESS":
      return ErrCode.SUCCESS;
    case 1:
    case "FAIL":
      return ErrCode.FAIL;
    case -1:
    case "UNRECOGNIZED":
    default:
      return ErrCode.UNRECOGNIZED;
  }
}

export function errCodeToJSON(object: ErrCode): string {
  switch (object) {
    case ErrCode.SUCCESS:
      return "SUCCESS";
    case ErrCode.FAIL:
      return "FAIL";
    case ErrCode.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

/** 响应码 */
export interface RespCode {
  errCode: ErrCode;
  msg?: string | undefined;
}

/** 心跳请求(速率: 10秒/1次 ) */
export interface HeartBeatReq {
}

/** 心跳响应 */
export interface HeartBeatResp {
  respCode: RespCode | undefined;
}

/** Ping */
export interface PingReq {
}

/** Pong */
export interface PongResp {
}

function createBaseRespCode(): RespCode {
  return { errCode: 0, msg: "" };
}

export const RespCode: MessageFns<RespCode> = {
  encode(message: RespCode, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.errCode !== 0) {
      writer.uint32(8).int32(message.errCode);
    }
    if (message.msg !== undefined && message.msg !== "") {
      writer.uint32(18).string(message.msg);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): RespCode {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRespCode();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.errCode = reader.int32() as any;
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.msg = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): RespCode {
    return {
      errCode: isSet(object.errCode) ? errCodeFromJSON(object.errCode) : 0,
      msg: isSet(object.msg) ? globalThis.String(object.msg) : "",
    };
  },

  toJSON(message: RespCode): unknown {
    const obj: any = {};
    if (message.errCode !== 0) {
      obj.errCode = errCodeToJSON(message.errCode);
    }
    if (message.msg !== undefined && message.msg !== "") {
      obj.msg = message.msg;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<RespCode>, I>>(base?: I): RespCode {
    return RespCode.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<RespCode>, I>>(object: I): RespCode {
    const message = createBaseRespCode();
    message.errCode = object.errCode ?? 0;
    message.msg = object.msg ?? "";
    return message;
  },
};

function createBaseHeartBeatReq(): HeartBeatReq {
  return {};
}

export const HeartBeatReq: MessageFns<HeartBeatReq> = {
  encode(_: HeartBeatReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartBeatReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartBeatReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): HeartBeatReq {
    return {};
  },

  toJSON(_: HeartBeatReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<HeartBeatReq>, I>>(base?: I): HeartBeatReq {
    return HeartBeatReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeartBeatReq>, I>>(_: I): HeartBeatReq {
    const message = createBaseHeartBeatReq();
    return message;
  },
};

function createBaseHeartBeatResp(): HeartBeatResp {
  return { respCode: undefined };
}

export const HeartBeatResp: MessageFns<HeartBeatResp> = {
  encode(message: HeartBeatResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.respCode !== undefined) {
      RespCode.encode(message.respCode, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): HeartBeatResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseHeartBeatResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.respCode = RespCode.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): HeartBeatResp {
    return { respCode: isSet(object.respCode) ? RespCode.fromJSON(object.respCode) : undefined };
  },

  toJSON(message: HeartBeatResp): unknown {
    const obj: any = {};
    if (message.respCode !== undefined) {
      obj.respCode = RespCode.toJSON(message.respCode);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<HeartBeatResp>, I>>(base?: I): HeartBeatResp {
    return HeartBeatResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<HeartBeatResp>, I>>(object: I): HeartBeatResp {
    const message = createBaseHeartBeatResp();
    message.respCode = (object.respCode !== undefined && object.respCode !== null)
      ? RespCode.fromPartial(object.respCode)
      : undefined;
    return message;
  },
};

function createBasePingReq(): PingReq {
  return {};
}

export const PingReq: MessageFns<PingReq> = {
  encode(_: PingReq, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PingReq {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePingReq();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PingReq {
    return {};
  },

  toJSON(_: PingReq): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PingReq>, I>>(base?: I): PingReq {
    return PingReq.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PingReq>, I>>(_: I): PingReq {
    const message = createBasePingReq();
    return message;
  },
};

function createBasePongResp(): PongResp {
  return {};
}

export const PongResp: MessageFns<PongResp> = {
  encode(_: PongResp, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PongResp {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePongResp();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(_: any): PongResp {
    return {};
  },

  toJSON(_: PongResp): unknown {
    const obj: any = {};
    return obj;
  },

  create<I extends Exact<DeepPartial<PongResp>, I>>(base?: I): PongResp {
    return PongResp.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PongResp>, I>>(_: I): PongResp {
    const message = createBasePongResp();
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
